title: Sheer Karny
description: >- # this means to ignore newlines until "baseurl:"
  This is my Jekyll site created to test and learn.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
url: "https://sheerkarny.github.io" # the base hostname & protocol for your site

markdown: kramdown
theme: minima

# Build settings
theme: minima
