title: Sheer Karny
description: >- # this means to ignore newlines until "baseurl:"
  This is my Jekyll site created to test and learn.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sheerkarny.github.io" # Update this to your GitHub Pages URL

markdown: kramdown
theme: minima

# Add these lines to ensure GitHub can find and use the theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optionally, you can specify which files to exclude from your site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
